Created Data Layer and UI Layer. Cleaned UI warnings.
blackcuarzo/examples-OOP-kotlin pull request #3
Opened 2022-06-16 03:20 UTC by blackcuarzo

- Moved fragments and activities to the UI layer.
- Moved Movie.kt and Movies.kt to the datalayer
- Cleaned pending warnings from the UI.

2022-06-16 16:15 UTC, estebanhiguitad requested changes
Agregar la capa de dominio. En la arquitectura es opcional, pero como objetivo de aprendizaje vamos a usarla.

2022-06-17 02:53 UTC, ldanielcano commented
New changes done:

- Created a MovieModel to be used by the application
- Created a MovieData object
- Created MovieLocalDataSource interface and MovieLocalDataSourceImpl 
- Used MovieLocalDataSource for inversion of dependencies
- Created a Repository and transformed the MovieData list into a MovieModel list

2022-06-17 03:03 UTC, ldanielcano reviewed
Confirm receipt

2022-06-22 06:23 UTC, closed without merging

2022-06-24 20:16 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/uilayer/menu/SearchFragment.kt
> +//        val moviesObserver = Observer<List<MovieModel>>{
eliminar código comentado

2022-06-24 20:16 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/uilayer/menu/HomeFragment.kt
> +//        val moviesObserver = Observer<List<MovieModel>>{
eliminar código comentado en todos los lugares que aplique en esta clase