Dc/week8 retrofit implementation
blackcuarzo/examples-OOP-kotlin pull request #5
Opened 2022-06-22 06:31 UTC by blackcuarzo

Did the retrofit implementation

2022-06-24 20:14 UTC, estebanhiguitad requested changes

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/Movies.kt
> +fun requestMoviesSource (): List<MovieDtoLocal> {
Sería bueno que esta función ya no exista, dado que se está usando un servicio web

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/MoviesDataLocal.kt
> +interface MoviesDataLocal {
Hay una convención para los data sources, que es poner la palabra DataSource al final, así que esta interfaz puede llamarse `MoviesLocalDataSource`

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/network/ImdbNetworkResponse.kt
> +data class ImdbNetworkResponse(
Para aclarar mejor la responsabilidad, sería bueno poner un nombre mucho más puntual de este data class

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/network/MoviesDataNetwork.kt
> +interface MoviesDataNetwork {
Aplicar la convención para que al final se llame DataSource

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/network/MovieDtoNetwork.kt
> +    )
Revisar siempre temas de la indentación

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/domainlayer/usecases/GetMoviesForUICaseImpl.kt
> +    override suspend fun getMovies(): List<MovieModel> {
Este comentario es solo para que tenga el conocimiento, mas no es necesario hacer un cambio. Los casos de uso, suelen implementarse con el operador invoke, que permite hacer un llamado al objeto y de forma implícita se llama la funcion.

https://kotlinlang.org/docs/operator-overloading.html#invoke-operator
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/invoke.html
https://chrynan.codes/invoking-usecases-the-kotlin-way/

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/uilayer/MovieViewHolder.kt
> +    fun bind(movie: MovieModel){
Revisar usa de este modelo en la interfaz, ya que veo que se tiene un modelo llamado MoviewUIModel

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/uilayer/uielements/menu/HomeFragment.kt
> +    private val viewModel by viewModels<MoviesViewModel>()
¿Cuál es la diferencia entre by viewModels y by activityViewModels?

2022-06-24 20:14 UTC, estebanhiguitad commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/uilayer/uielements/menu/MovieDetailsFragment.kt
> +            view.findViewById<ImageView>(R.id.previewImage).load(args.preview)
Recuerda la migración para usar viewBinding

2022-06-27 00:05 UTC, blackcuarzo commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/Movies.kt
> +fun requestMoviesSource (): List<MovieDtoLocal> {
Cambios hechos, también eliminé la implementación que tenía de LocalDataSource. Debería eliminar el Dto y la interfaz de LocalDataSource?

2022-06-27 00:05 UTC, blackcuarzo commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/MoviesDataLocal.kt
> +interface MoviesDataLocal {
Cambio hecho, gracias por el feedback

2022-06-27 00:11 UTC, blackcuarzo commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/network/ImdbNetworkResponse.kt
> +data class ImdbNetworkResponse(
Pasé a llamarlo ImdbApiServiceResponse, y la función que lo llama en MoviesApiService pasó a llamarse getApiResponse. 
```kotlin 
interface MoviesApiService {  
    @GET("movie/top_rated?api_key=${API_KEY}&language=es")  
    suspend fun getApiResponse(): ImdbApiServiceResponse  
}
```
Ahora en MoviesNetworkDataSourceImpl, paso a llamar el atributo "results" y entrego directamente la lista: 
```kotlin
override suspend fun getMoviesList(): List<MovieDtoNetwork> {  
    return MoviesApi.retrofitService.getApiResponse().results  
}
```

2022-06-27 00:11 UTC, blackcuarzo commented on IMDbApp/app/src/main/java/com/danielcano/imdbapp/datalayer/datasources/network/MovieDtoNetwork.kt
> +    )
Cambios hechos, gracias por el feedback

2022-07-02 00:02 UTC, closed without merging